############################################################################################
###################################### 运行容器端口设置 ##########################################
############################################################################################
server:
  port: 8080
JASYPT_PASS: ByYing&^  
############################################################################################
######################################## jasypt ############################################
############################################################################################
jasypt:
    encryptor:
        password: ${JASYPT_PASS:}
############################################################################################
######################################### pwd ##############################################
############################################################################################
pwd: ENC(+nVNImCkra0NKOX/wTy7iMutNZohx3YJ)