############################################################################################
###################################### 运行容器端口设置 ##########################################
############################################################################################
server:
  port: 8080
JASYPT_PASS: 9e5eb701949a152dabb25af9a21b764f2439fa9dd76437d4209bbee8088a1be5
############################################################################################
######################################## jasypt ############################################
############################################################################################
jasypt:
    encryptor:
        password: ${JASYPT_PASS:}
############################################################################################
######################################### pwd ##############################################
############################################################################################
pwd: ENC(1EnLd3e1TMY2pifbPKVXZg==)